select * from churn limit 2;
select * from customers limit 2;
select * from subscriptions limit 2;
select * from transactions limit 2;

select * from customers;
select FirstName, LastName from customers;
select * from customers where Region = 'north america';
select count(distinct CustomerID) from customers;
select * from customers where status = 'active';
select count(*) from customers where status = 'active';
select * from customers where cast(JoinDate as date) > '2021-01-01';
select * from customers where Region = 'europe' and status = 'active';
select * from customers ;

---year---2021
select * from customers 
where year(cast(JoinDate as Date)) = 2021;

select * from customers
where Email = 'john.doe@example.com';

--------------------------------
select * from customers
where email like '%example%';

select * from subscriptions
where plantype = 'annual';

select count(*) from subscriptions
where plantype = 'annual';

----avg transaction amount

select avg(amount)
from transactions;

transaction amt > 100-----

select * from transactions
where amount > 100;


transaction about customer id 1---
select * from transactions
where CustomerID = 1;

trans info with first name and last name----

SELECT firstname, lastname, t.*
from customers c join transactions t
on c.customerid=t.customerid

find the recent trans---
select max(transactiondate)
from transactions;

churn reason---
select distinct reason
from churn;

count of customer who churn-----

select count(distinct CustomerID)
from churn;

customer who churned cause of price---

select * from churn
where reason like '%price%'

join customers and subscriptions-----

select *
from customers c join subscriptions s
on c.customerid = s.customerid;

customers where subscription is annual

select * from subscriptions
where plantype = 'annual';

select *
from customers c join subscriptions s
on c.customerid = s.customerid
where plantype = 'annual';

--calculate total revenue
select sum(amount)
from transactions;

select * from churn limit 2
# customers who have not churned

select * from customers
where CustomerID NOT IN
(SELECT DISTINCT CUSTOMERID FROM CHURN);

SELECT *
FROM CUSTOMERS LEFT JOIN CHURN
ON CUSTOMERID != CUSTOMERID;

SELECT *
FROM CUSTOMERS c
LEFT JOIN CHURN ch
ON c.CUSTOMERID != ch.CUSTOMERID;

#FIND CUSTOMER AND TOTAL SPEND, CUSTOMER AND TOTAL SPEND

SELECT FirstName, C.CustomerID, SUM(AMOUNT)
FROM CUSTOMERS C JOIN transactions T
ON C.CustomerID = T.CustomerID
group by FirstName, C.CustomerID


#Select all subscriptions that ended in the year 2022
SELECT * FROM subscriptions
WHERE YEAR(CONVERT(DATE,ENDDATE,105)) = 2022;


SELECT *
FROM subscriptions
WHERE YEAR(ENDDATE) = 2022;

SELECT *
FROM subscriptions
WHERE YEAR(STR_TO_DATE(ENDDATE, '%d-%m-%Y')) = 2022;

#Retrieve all transactions that are not of type 'Renewal
SELECT * FROM transactions
WHERE TransactionType != 'RENEWAL'

#Retrieve all customers who have churned and have made transactions.

SELECT *
FROM CUSTOMERS C JOIN TRANSACTIONS T
ON C.CUSTOMERID = T.CUSTOMERID;

# Find the earliest join date among all customers.

SELECT * min (STR_TO_DATE(JOINDATE, '%d-%m-%Y')
from customers;

SELECT MIN(STR_TO_DATE(JOINDATE, '%d-%m-%Y'))
FROM customers;

#Select all subscriptions that ended in January 2023.

SELECT * FROM subscriptions
WHERE DATE(STR_TO_DATE(ENDDATE, '%d-%m-%Y')) = 01-2023;

SELECT *
FROM subscriptions
WHERE STR_TO_DATE(ENDDATE, '%d-%m-%Y') = '2023-01-01';

#Retrieve all customers who have not made any transactions.

SELECT * FROM CUSTOMERS WHERE CustomerID NOT IN (SELECT CUSTOMERID FROM transactions);

SELECT *
FROM CUSTOMERS C LEFT JOIN TRANSACTIONS T
on c.customerid=t.customerid
where transactionid is null;

#Retrieve all customers who do not have any subscriptions.
SELECT * FROM CUSTOMERS WHERE CustomerID NOT IN (SELECT CUSTOMERID FROM subscriptions);

SELECT *
FROM CUSTOMERS C LEFT JOIN subscriptions s
on c.customerid=s.customerid
where subscriptionid is null;

#Calculate the average transaction amount for each customer.

SELECT FirstName, C.CustomerID, avg(AMOUNT)
FROM CUSTOMERS C JOIN transactions T
ON C.CustomerID = T.CustomerID
group by FirstName, C.CustomerID

#Identify the top 3 regions with the highest number of customers.

select top 3 region, count(*)
from customers
group by region
order by count (*) desc

SELECT region, COUNT(*) 
FROM customers
GROUP BY region
ORDER BY COUNT(*) DESC
LIMIT 3;

#Calculate the total revenue generated by customers in each region.

SELECT Region, SUM(Amount)
FROM Customers C
JOIN Transactions T
ON C.CustomerID = T.CustomerID
GROUP BY Region;

#Identify the most frequently cited reason for customer churn.

SELECT REASON, COUNT(*), 
FROM CHURN
GROUP BY REASON;

SELECT REASON, COUNT(*) AS total
FROM CHURN
GROUP BY REASON;

SELECT REASON, COUNT(*)
FROM CHURN
GROUP BY REASON
ORDER BY COUNT(*) DESC;

#Retrieve customers who have not made any transactions.
SELECT *
FROM Customers C
JOIN Transactions T
ON C.CustomerID = T.CustomerID
WHERE TransactionType IS 'NULL';

SELECT *
FROM Customers C LEFT JOIN Transactions T
ON C.CustomerID = T.CustomerID
WHERE TransactionID IS NULL;

#Compare the total revenue generated by active and inactive customers.

SELECT STATUS, SUM(AMOUNT)
FROM Customers C JOIN Transactions T
ON C.CustomerID = T.CustomerID
WHERE STATUS IN ('ACTIVE', 'INACTIVE') 
GROUP BY STATUS;

#Identify customers who have been with the company the longest.
SELECT C.CUSTOMERID,DATEDIFF(DAY,JOINDATE, CONVERT(DATE,ENDDATE,105)) DURATION
FROM CUSTOMER C JOIN SUBSCRIPTION S
ON C.CUSTOMERID=S.CUSTOMERID
ORDER BY DURATION DESC;

SELECT 
    C.CUSTOMERID,
    DATEDIFF(
        STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
        C.JOINDATE
    ) AS DURATION
FROM CUSTOMERS C
JOIN SUBSCRIPTIONS S
ON C.CUSTOMERID = S.CUSTOMERID
ORDER BY DURATION DESC;

WITH CTE AS(
SELECT 
    C.CUSTOMERID,
    DATEDIFF(
        STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
        C.JOINDATE
    ) AS DURATION
FROM CUSTOMER C
JOIN SUBSCRIPTION S
ON C.CUSTOMERID = S.CUSTOMERID
, CTE2 AS(
SELECT * , DENSE_RANK() OVER(ORDER BY DURATION DESC) DR
FROM CTE)
SELECT * FROM CTE2
WHERE DR=1

ORDER BY DURATION DESC;


SELECT CUSTOMERID, DURATION
FROM (
    SELECT 
        C.CUSTOMERID,
        DATEDIFF(
            STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
            STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
        ) AS DURATION,
        DENSE_RANK() OVER (
            ORDER BY DATEDIFF(
                STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
                STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
            ) DESC
        ) AS rnk
    FROM CUSTOMERS C
    JOIN SUBSCRIPTIONS S
        ON C.CUSTOMERID = S.CUSTOMERID
) t
WHERE rnk = 1;

SELECT *
FROM (
    SELECT 
        C.CUSTOMERID,
        DATEDIFF(
            STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
            STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
        ) AS DURATION
    FROM CUSTOMERS C
    JOIN SUBSCRIPTIONS S
        ON C.CUSTOMERID = S.CUSTOMERID
) X
WHERE DURATION = (
    SELECT MAX(
        DATEDIFF(
            STR_TO_DATE(S.ENDDATE, '%d-%m-%Y'),
            STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
        )
    )
    FROM CUSTOMERS C
    JOIN SUBSCRIPTIONS S
        ON C.CUSTOMERID = S.CUSTOMERID
);


#Calculate the average time between a customer joining and churning.

SELECT 
        AVERAGE(
        DATEDIFF(
            STR_TO_DATE(S.ChurnDate, '%d-%m-%Y'),
            STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
        ) AS DURATION
        
        
        SELECT 
    AVG(
        DATEDIFF(
            STR_TO_DATE(S.ChurnDate, '%d-%m-%Y'),
            STR_TO_DATE(C.JOINDATE, '%d-%m-%Y')
        )
    ) AS DURATION
FROM CUSTOMERS C
JOIN CHURN S
    ON C.CUSTOMERID = S.CUSTOMERID;
    

#Identify customers who have renewed their subscription at least once.
SELECT CUSTOMERID, COUNT(*) AS renewal_count
FROM transactions
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;

SELECT C.*
FROM CUSTOMERS C
JOIN (
    SELECT CUSTOMERID
    FROM transactions
    GROUP BY CUSTOMERID
    HAVING COUNT(*) > 1
) R
ON C.CUSTOMERID = R.CUSTOMERID;

SELECT CUSTOMERID
FROM transactions
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;

#Rank regions based on average revenue per customer.
SELECT Region, AVG(TotalSpend) AS AvgRevenuePerCustomer
FROM (
    SELECT C.CustomerID, Region, SUM(Amount) AS TotalSpend
    FROM Customers C
    JOIN Transactions T 
    ON C.CustomerID = T.CustomerID
    GROUP BY CustomerID, Region
) AS CustomerSpending
GROUP BY Region
ORDER BY AvgRevenuePerCustomer DESC;

WITH CTE AS(
SELECT REGION, AVG(AMOUNT) AVERAGE
FROM CUSTOMERS C JOIN TRANSACTIONS T
ON C.CUSTOMERID=T.CUSTOMERID
GROUP BY REGION)
SELECT *, dense_rank() OVER(ORDER BY AVERAGE DESC)
FROM CTE

#Identify the top 5 most profitable customers based on their total spending.

SELECT C.CUSTOMERID, FIRSTNAME, SUM(AMOUNT) AS TOTAL SPEND
FROM CUSTOMERS C JOIN TRANSACTIONS T
ON C.CUSTOMERID = T.CUSTOMERID
GROUP BY C.CUSTOMERID, FIRSTNAME
ORDER BY TOTAL SPEND DESC
LIMIT 5;

SELECT 
    C.CUSTOMERID,
    FIRSTNAME,
    SUM(AMOUNT) AS TOTAL_SPEND
FROM CUSTOMERS C 
JOIN TRANSACTIONS T
    ON C.CUSTOMERID = T.CUSTOMERID
GROUP BY C.CUSTOMERID, FIRSTNAME
ORDER BY TOTAL_SPEND DESC
LIMIT 5;

#Retrieve a list of customers who share the same last name.
SELECT CUSTOMERID, FIRSTNAME 
FROM CUSTOMERS
WHERE LASTNAME 

#Identify Regions with High Churn Rates
REGION NUMBER-CHURN CUST

SELECT REGION, COUNT(CH.CUSTOMERID) AS CHURN_C, COUNT(*) AS TOTAL,
COUNT(CH.CUSTOMERID)*100/COUNT(*) AS PERCENTAGE
FROM CUSTOMERS C LEFT JOIN CHURN CH
ON C.CUSTOMERID = CH.CUSTOMERID
GROUP BY REGION

#Calculate the monthly revenue growth over the last year.

SELECT 
    DATE_FORMAT(STR_TO_DATE(TransactionDate, '%d-%m-%Y'), '%Y-%m') AS Month,
    SUM(Amount) AS MonthlyRevenue
FROM Transactions
WHERE STR_TO_DATE(TransactionDate, '%d-%m-%Y') >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR)
GROUP BY Month
ORDER BY Month;